<a href="https://colab.research.google.com/github/unnimaya-vu/unnimaya-vu/blob/main/creditscorealalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Credit Score Classification Dataset (1).csv')
df

Age  Gender    Income            Education Marital Status  \
0     25  Female   50000.0    Bachelor's Degree         Single   
1     30    Male  100000.0      Master's Degree        Married   
2     35  Female   75000.0            Doctorate        Married   
3     40    Male  125000.0  High School Diploma         Single   
4     45  Female  100000.0    Bachelor's Degree        Married   
..   ...     ...       ...                  ...            ...   
159   29  Female   27500.0  High School Diploma         Single   
160   34    Male   47500.0   Associate's Degree         Single   
161   39  Female   62500.0    Bachelor's Degree        Married   
162   44    Male   87500.0      Master's Degree         Single   
163   49  Female   77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [ ]:
df.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [ ]:
#filling missing values
m=df['Gender'].mode()[0]
df['Gender'].fillna(m,inplace=True)
m1=df['Income'].mean()
df['Income'].fillna(m1,inplace=True)
df

Age  Gender    Income            Education Marital Status  \
0     25  Female   50000.0    Bachelor's Degree         Single   
1     30    Male  100000.0      Master's Degree        Married   
2     35  Female   75000.0            Doctorate        Married   
3     40    Male  125000.0  High School Diploma         Single   
4     45  Female  100000.0    Bachelor's Degree        Married   
..   ...     ...       ...                  ...            ...   
159   29  Female   27500.0  High School Diploma         Single   
160   34    Male   47500.0   Associate's Degree         Single   
161   39  Female   62500.0    Bachelor's Degree        Married   
162   44    Male   87500.0      Master's Degree         Single   
163   49  Female   77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [ ]:
df.isna().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [ ]:

from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
#label encoding of a dataframe
df['Gender']=lab.fit_transform(df['Gender'])
df['Education']=lab.fit_transform(df['Education'])
df['Marital Status']=lab.fit_transform(df['Marital Status'])
df['Home Ownership']=lab.fit_transform(df['Home Ownership'])
df

Age  Gender    Income  Education  Marital Status  Number of Children  \
0     25       0   50000.0          1               1                   0   
1     30       1  100000.0          4               0                   2   
2     35       0   75000.0          2               0                   1   
3     40       1  125000.0          3               1                   0   
4     45       0  100000.0          1               0                   3   
..   ...     ...       ...        ...             ...                 ...   
159   29       0   27500.0          3               1                   0   
160   34       1   47500.0          0               1                   0   
161   39       0   62500.0          1               0                   2   
162   44       1   87500.0          4               1                   0   
163   49       0   77500.0          2               0                   1   

     Home Ownership Credit Score  
0                 1         High  
1                 0         High  
2                 0         High  
3                 0         High  
4                 0         High  
..              ...          ...  
159               1          Low  
160               1      Average  
161               0         High  
162               0         High  
163               0         High  

[164 rows x 8 columns]

In [ ]:
#splitting train and test data
x1=df.iloc[:,:-1].values
y1=df.iloc[:,-1].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.30,random_state=1)
x_train

array([[4.90000000e+01, 0.00000000e+00, 6.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 8.75000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 1.22500000e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.20000000e+01, 1.00000000e+00, 1.25000000e+05, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 6.75000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.12500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.50000000e+04, 0.00000000e+00,
        1.00000000e+00, 0

In [ ]:
#Normalisation using Standard scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 1.33092878, -0.9655068 , -0.64521889, -0.07634181, -0.9655068 ,
         0.3683942 , -0.66561098],
       [ 0.71913088,  1.03572548,  0.08392774,  1.37415257,  1.03572548,
        -0.7367884 , -0.66561098],
       [-0.38210536, -0.9655068 ,  0.00291145, -0.07634181, -0.9655068 ,
         0.3683942 , -0.66561098],
       [ 1.82036711,  1.03572548,  1.21815585, -1.52683619, -0.9655068 ,
        -0.7367884 , -0.66561098],
       [ 1.69800753,  1.03572548,  1.29917214,  0.64890538, -0.9655068 ,
        -0.7367884 , -0.66561098],
       [-0.01502662, -0.9655068 , -0.5642026 , -0.801589  , -0.9655068 ,
         1.4735768 , -0.66561098],
       [-0.99390327,  1.03572548,  0.89409068,  1.37415257, -0.9655068 ,
         1.4735768 , -0.66561098],
       [-0.74918411,  1.03572548, -0.96928407, -1.52683619,  1.03572548,
        -0.7367884 ,  1.50237907],
       [ 0.59677129,  1.03572548, -0.03106312,  1.37415257,  1.03572548,
        -0.7367884 , -0.66561098],
       [-1.23862243, -0.9655

In [ ]:
#Model creation by knn,naivebayes,svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report
k_model=KNeighborsClassifier(n_neighbors=7)
n_model=GaussianNB()
s_model=SVC()
lst_model=[k_model,n_model,s_model]


In [ ]:
#Evaluating the model
for i in lst_model:
  print('Model is',i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print('*'*50)
  print(confusion_matrix(y_test,y_pred))
  print('Accuracy score is',accuracy_score(y_test,y_pred))
  print('-------Classification Report-----------')
  print(classification_report(y_test,y_pred))


Model is KNeighborsClassifier(n_neighbors=7)
**************************************************
[[11  1  0]
 [ 0 31  0]
 [ 3  0  4]]
Accuracy score is 0.92
-------Classification Report-----------
              precision    recall  f1-score   support

     Average       0.79      0.92      0.85        12
        High       0.97      1.00      0.98        31
         Low       1.00      0.57      0.73         7

    accuracy                           0.92        50
   macro avg       0.92      0.83      0.85        50
weighted avg       0.93      0.92      0.92        50

Model is GaussianNB()
**************************************************
[[ 6  1  5]
 [ 0 31  0]
 [ 2  0  5]]
Accuracy score is 0.84
-------Classification Report-----------
              precision    recall  f1-score   support

     Average       0.75      0.50      0.60        12
        High       0.97      1.00      0.98        31
         Low       0.50      0.71      0.59         7

    accuracy                    